// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///  import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb_bCWq33UsMjFMDo6xYTpBTLL1ZCDMI8',
    appId: '1:743929462218:web:194691db35d21c28202333',
    messagingSenderId: '743929462218',
    projectId: 'riderapp-79654',
    authDomain: 'riderapp-79654.firebaseapp.com',
    storageBucket: 'riderapp-79654.appspot.com',
    measurementId: 'G-YFM4SPN9CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ9IKHEcNP7KLOzU5RrCJ-JmJdli7lBrk',
    appId: '1:743929462218:android:7dd4ec661e5a2b86202333',
    messagingSenderId: '743929462218',
    projectId: 'riderapp-79654',
    storageBucket: 'riderapp-79654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP0mDnvanj9rXa0IOvl_oz9y6VCXH_9xY',
    appId: '1:743929462218:ios:5225f004161cf0fa202333',
    messagingSenderId: '743929462218',
    projectId: 'riderapp-79654',
    storageBucket: 'riderapp-79654.appspot.com',
    iosClientId:
        '743929462218-4dpfal2b5gn8dh6gc5bb5i3khlvokd5l.apps.googleusercontent.com',
    iosBundleId: 'com.ugocode.riderApp',
  );
}
